"""Tests for the Agent-side edit loop: digest, merge, drift, status."""

from __future__ import annotations

import json

import pytest

import lib.edit_apply as ea
import lib.edit_intents as ei


def _sample_cuts():
    return [
        {"id": "c01", "source": "assets/video/seg01.mp4", "in_seconds": 0.0, "out_seconds": 4.0},
        {"id": "c02", "source": "assets/video/seg02.mp4", "in_seconds": 1.2, "out_seconds": 6.5},
        {"id": "c03", "source": "assets/video/seg03.mp4", "in_seconds": 2.0, "out_seconds": 5.0},
        {"id": "c04", "source": "assets/video/seg04.mp4", "in_seconds": 0.5, "out_seconds": 3.2},
    ]


@pytest.fixture
def project(monkeypatch, tmp_path):
    root = tmp_path / "projects"
    p = root / "demo-pro"
    (p / "artifacts").mkdir(parents=True)
    (p / "intents").mkdir(parents=True)
    (p / "artifacts" / "edit_decisions.json").write_text(json.dumps({
        "version": "1.0",
        "render_runtime": "ffmpeg",
        "cuts": _sample_cuts(),
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    monkeypatch.setattr(ea, "PROJECTS_DIR", root)
    monkeypatch.setattr(ei, "PROJECTS_DIR", root)
    return p


def _intent(project_id="demo-pro", **overrides):
    data = {
        "version": "1.0",
        "intent_id": "intent-t1",
        "project_id": project_id,
        "created_at": "2026-08-12T00:00:00+00:00",
        "status": "pending",
        "base": {"artifact": "edit_decisions", "cuts_revision": ea.cuts_digest(_sample_cuts())},
        "actions": [{"type": "delete", "cut_id": "c03"}],
    }
    data.update(overrides)
    return data


# ---- digest cross-language consistency ------------------------------------

def test_digest_matches_board_generated_revision():
    # The revision string was generated by board-edit.js in the browser for the
    # exact same 4-cut sample (intent-1786448389352.json, base.cuts_revision).
    assert ea.cuts_digest(_sample_cuts()) == "h1gohvfo"


def test_digest_changes_when_cuts_change():
    cuts = _sample_cuts()
    base = ea.cuts_digest(cuts)
    cuts[0]["out_seconds"] = 5.0
    assert ea.cuts_digest(cuts) != base


# ---- apply / merge --------------------------------------------------------

def test_apply_delete(project):
    ei.create_intent("demo-pro", _intent(actions=[{"type": "delete", "cut_id": "c03"}]))
    result = ea.apply_intent("demo-pro", "intent-t1")
    assert result["applied"] is True
    cuts = ea.load_edit_decisions("demo-pro")["cuts"]
    assert [c["id"] for c in cuts] == ["c01", "c02", "c04"]
    assert result["removed_cuts"] == ["c03"]
    assert result["friendly_zh"]


def test_apply_trim_writes_reason(project):
    ei.create_intent("demo-pro", _intent(actions=[
        {"type": "trim", "cut_id": "c02", "in_seconds": 1.5, "out_seconds": 7.0},
    ]))
    ea.apply_intent("demo-pro", "intent-t1")
    c02 = next(c for c in ea.load_edit_decisions("demo-pro")["cuts"] if c["id"] == "c02")
    assert c02["in_seconds"] == 1.5
    assert c02["out_seconds"] == 7.0
    assert c02["reason"] == "user intent intent-t1"


def test_apply_reorder(project):
    ei.create_intent("demo-pro", _intent(actions=[
        {"type": "reorder", "order": ["c04", "c01", "c03", "c02"]},
    ]))
    ea.apply_intent("demo-pro", "intent-t1")
    ids = [c["id"] for c in ea.load_edit_decisions("demo-pro")["cuts"]]
    assert ids == ["c04", "c01", "c03", "c02"]


def test_apply_combined_like_user_submission(project):
    # Mirrors the real board submission: delete c03 + reorder [c02, c04, c01].
    ei.create_intent("demo-pro", _intent(actions=[
        {"type": "delete", "cut_id": "c03"},
        {"type": "reorder", "order": ["c02", "c04", "c01"]},
    ]))
    ea.apply_intent("demo-pro", "intent-t1")
    ids = [c["id"] for c in ea.load_edit_decisions("demo-pro")["cuts"]]
    assert ids == ["c02", "c04", "c01"]


def test_apply_keeps_non_cuts_fields(project):
    ei.create_intent("demo-pro", _intent(actions=[{"type": "delete", "cut_id": "c03"}]))
    ea.apply_intent("demo-pro", "intent-t1")
    data = ea.load_edit_decisions("demo-pro")
    assert data["render_runtime"] == "ffmpeg"
    assert data["version"] == "1.0"


def test_apply_marks_intent_applied(project):
    ei.create_intent("demo-pro", _intent())
    ea.apply_intent("demo-pro", "intent-t1")
    assert ei.get_intent("demo-pro", "intent-t1")["status"] == "applied"


def test_apply_again_rejected(project):
    ei.create_intent("demo-pro", _intent())
    ea.apply_intent("demo-pro", "intent-t1")
    with pytest.raises(ei.IntentError):
        ea.apply_intent("demo-pro", "intent-t1")


def test_missing_cut_skipped_others_applied(project):
    ei.create_intent("demo-pro", _intent(actions=[
        {"type": "delete", "cut_id": "ghost"},
        {"type": "delete", "cut_id": "c02"},
    ]))
    result = ea.apply_intent("demo-pro", "intent-t1")
    assert result["applied"] is True
    ids = [c["id"] for c in ea.load_edit_decisions("demo-pro")["cuts"]]
    assert "c02" not in ids and "ghost" not in ids
    assert ids == ["c01", "c03", "c04"]


def test_missing_intent_raises(project):
    with pytest.raises(ei.IntentError):
        ea.apply_intent("demo-pro", "ghost")


# ---- drift ----------------------------------------------------------------

def test_drift_marks_superseded_and_does_not_apply(project):
    ei.create_intent("demo-pro", _intent())
    # Change the cuts on disk after the intent was created.
    data = ea.load_edit_decisions("demo-pro")
    data["cuts"][0]["out_seconds"] = 6.0
    ea.save_edit_decisions("demo-pro", data)

    result = ea.apply_intent("demo-pro", "intent-t1")
    assert result["applied"] is False
    assert result["reason"] == "drift"
    assert "旧版本" in result["friendly_zh"]
    assert ei.get_intent("demo-pro", "intent-t1")["status"] == "superseded"
    # cuts untouched
    assert ea.load_edit_decisions("demo-pro")["cuts"][0]["out_seconds"] == 6.0


# ---- plan text / inbox ----------------------------------------------------

def test_plan_text_lists_actions():
    text = ea.plan_text(_intent(actions=[
        {"type": "trim", "cut_id": "c01", "in_seconds": 0.0, "out_seconds": 3.0},
        {"type": "delete", "cut_id": "c03"},
        {"type": "reorder", "order": ["c02", "c01", "c04"]},
        {"type": "delete", "cut_id": "c99", "note": "这段不要了"},
    ]))
    assert "c01 时长改为 0.0–3.0 秒" in text
    assert "删除片段 c03" in text
    assert "调整片段顺序" in text
    assert "这段不要了" in text


def test_list_pending_filters_status(project):
    ei.create_intent("demo-pro", _intent(intent_id="a", status="pending"))
    ei.create_intent("demo-pro", _intent(intent_id="b", status="confirmed"))
    ids = [i["intent_id"] for i in ea.list_pending("demo-pro")]
    assert ids == ["a"]


# ---- note-only intents ---------------------------------------------------

def test_apply_note_only_intent(project):
    ei.create_intent("demo-pro", _intent(actions=[], note="字幕换中文"))
    result = ea.apply_intent("demo-pro", "intent-t1")
    assert result["applied"] is True
    assert result["cut_count"] == {"before": 4, "after": 4}
    assert "按备注处理" in result["friendly_zh"]
    assert len(ea.load_edit_decisions("demo-pro")["cuts"]) == 4
    assert ei.get_intent("demo-pro", "intent-t1")["status"] == "applied"


def test_plan_text_uses_top_level_note():
    text = ea.plan_text(_intent(actions=[], note="节奏放慢"))
    assert "用户备注：节奏放慢" in text
